### ISSUE TITLE
fill in  missing wiki sections

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/SMBE2024Workshop#14]
just copy across the content from cogent3 workshop and maybe link directly to resource files from the original

- working with cogent3 env
- putting files in place

**Comment by GavinHuttley** [comment]
I'll add text describing the download for the installed apes tarball when I've finished that

**Comment by khiron** [comment]
Content copied across from phylomania workshop.

suggest having a recipe for "here's how you download the apes yourself" in the data directory using the config file in that directory, or here's a zip we prepared earlier that you can wget and unpack directly into your data directory.

**Comment by GavinHuttley** [comment]
@khiron but there are two sections missing on [this page](https://github.com/cogent3/SMBE2024Workshop/wiki/Configuring-your-environment)

**Comment by GavinHuttley** [comment]
turns out the links on that navigation page were not updated, done
