### ISSUE TITLE
demo data set and installation

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/SMBE2024Workshop#6]
- [x] @khiron are there limits on how big an image can be on dockerhub?
- [x] @khiron investigate how we can share a ~6GB ensembl_lite data installation
- [x] @GavinHuttley can we get by with just 3 great apes?

**Comment by khiron** [comment]
## How to find out how large a docker container is
`docker ps -s`

In the case of the container created from the current DockerFile it is 3.24GB

**Comment by khiron** [comment]
There is apparently no synthetic limit on size of an image on DockerHub, although it is recommended that layers should not be greater than 10-20GB.  

A layer is an image upon which a further DockerFile builds upon.  

So in the case of our container here our layers are 

- **debian bookworm-slim** - cut down version of debian linux
- **continuumIO/miniconda3 image** adding all the conda infrastructure

I suspect we likely want to add 3 more layers on DockerHub

- **cogent3Workshop**: our instructions for cloning and flit installing cogent3 and  setting up the c312 environment, zshell, oh my zsh, and the non-root account.
- **EnsemblLiteWorkshop**: that builds from the base cogent3Workshop to clone and flit install EnsembleLite
- **EnsemblLite3PrimateWorkshop**: additionally includes the data for 3 primate genomes

I have a private DockerHub account that I created when we build the Phylomania workshop.  It is limited to 200 downloads of images in any 6 hour period. 

I can upgrade that for free to an organizational account for the lab that would remove that restriction, and the only requirements to have that for free is less than 250 team members (not workshop attendees, just members able to upload to our account) and be non-commercial.

I am looking into whether we should also sign up for being a Docker Sponsored open source project https://www.docker.com/community/open-source/application/ which doesn't give us many features other than using our project's logo and branding, and visibility on their site among other OSS projects.

**Comment by khiron** [comment]
BTW I'm also looking into skipping DockerHub entirely and using github packages which may do the same thing in the same stack as our code

https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages

**Comment by GavinHuttley** [comment]
Closing as I think this has been dealt with
